version: '3'

services:
   salesforce:
     image: qip-work-salesforce
     ports:
      - "5000:5000"
     restart: always
     volumes:
      - data:/home/node/app/data
      
volumes:
  data:
    driver: local
    driver_opts:
       o: bind
       type: none
       device: /home/squadra/Área de Trabalho/generetedCode/work/data